import React from 'react';
import Head from 'next/head';

// components
import Header from '../../components/header/Header';
import Content, { StatCards } from '../../components/planet/Content';
import Controls from '../../components/planet/Controls';
import PlanetGrid from '../../components/PlanetGrid';
import PlanetImage from '../../components/planet/PlanetImage';

export default function Planet() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Planets Fact Site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <PlanetGrid>
          <PlanetImage />
          <Content />
          <StatCards />
          <Controls />
        </PlanetGrid>
      </main>
    </>
  );
}
