import React from 'react';
import Head from 'next/head';

// components
import Header from '../../components/header/Header';
import Content, { StatCards } from '../../components/planet/Content';
import Controls from '../../components/planet/Controls';
import PlanetGrid from '../../components/PlanetGrid';
import PlanetImage from '../../components/planet/PlanetImage';
import PlanetModel from '../../models/Planet';

export default function Planet({ planetData }: { planetData: PlanetModel }) {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Planets Fact Site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <PlanetGrid>
          <p>{planetData.name}</p>
          <PlanetImage />
          <Content />
          <StatCards />
          <Controls />
        </PlanetGrid>
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const res = await fetch('http://localhost:3000/api/planets');
  const data = await res.json();

  const planetData = await data.find(
    (planet: PlanetModel) =>
      planet.name.toLowerCase() === context.query.id.toLowerCase()
  );

  console.log(context.query);

  return {
    props: { planetData },
  };
}
