import Head from 'next/head';
import Image from 'next/image';

// components
import Header from '../components/header/Header';
import PlanetModel from '../models/Planet';
import HomePlanet from '../components/HomePlanet';

export default function Home({ data }: { data: PlanetModel[] }) {
  console.log(data[0].images);
  return (
    <>
      <Head>
        <title>Frontend Mentor | Planets Fact Site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <ul className='grid grid-cols-1 text-center md:grid-cols-2 lg:grid-cols-3 max-w-7xl mx-auto'>
          {data.map((planet) => {
            return <HomePlanet key={planet.name} data={planet} />;
          })}
        </ul>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/planets');
  const data = await res.json();

  return {
    props: { data },
  };
}
