import Head from 'next/head';

// components
import Header from '../components/header/Header';
import Content, { StatCards } from '../components/planet/Content';
import Controls from '../components/planet/Controls';
import Planet from '../components/planet/Planet';
import PlanetGrid from '../components/PlanetGrid';

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Planets Fact Site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <PlanetGrid>
          <Planet />
          <Content />
          <StatCards />
          <Controls />
        </PlanetGrid>
      </main>
    </>
  );
}
