import Head from 'next/head';
import Header from '../components/header/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Planets Fact Site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main></main>
    </>
  );
}
